import {
  Form,
  FormItem,
  Input,
  Button,
  Card,
  Container,
  Aside,
  Menu,
  Submenu,
  MenuItem,
  Header,
  Breadcrumb,
  BreadcrumbItem,
  Dropdown,
  DropdownMenu,
  DropdownItem,
  Avatar,
  Main,
  Table,
  DatePicker,
  TableColumn,
  Dialog,
  Select,
  Switch,
  Option,
  Pagination,
  Steps,
  Step,
  Upload,
  Progress,
  Link,
  Radio,
  RadioGroup,
  InputNumber,
  Tree,
  Loading
} from 'element-ui'

export default {
  install (Vue) {
    Vue.use(Form)
    Vue.use(FormItem)
    Vue.use(Input)
    Vue.use(Button)
    Vue.use(Card)
    Vue.use(Container)
    Vue.use(Aside)
    Vue.use(Menu)
    Vue.use(Submenu)
    Vue.use(MenuItem)
    Vue.use(Header)
    Vue.use(Breadcrumb)
    Vue.use(BreadcrumbItem)
    Vue.use(Avatar)
    Vue.use(Dropdown)
    Vue.use(DropdownMenu)
    Vue.use(DropdownItem)
    Vue.use(Main)
    Vue.use(Table)
    Vue.use(DatePicker)
    Vue.use(Table)
    Vue.use(TableColumn)
    Vue.use(Dialog)
    Vue.use(Select)
    Vue.use(Switch)
    Vue.use(Option)
    Vue.use(Pagination)
    Vue.use(Steps)
    Vue.use(Step)
    Vue.use(Upload)
    Vue.use(Progress)
    Vue.use(Link)
    Vue.use(Radio)
    Vue.use(RadioGroup)
    Vue.use(InputNumber)
    Vue.use(Tree)
    Vue.use(Loading.directive)
  }
}
